export default {
  menu: {
    data: {
      pageNum: 1,
      pageSize: 10,
      total: 8,
      list: [
        {
          id: 10,
          parentId: 1,
          path: "/system",
          name: "system",
          component: "Layout",
          redirect: "/system/userList",
          isHide: false,
          meta: {
            title: "system",
            icon: "system",
            isKeepAlive: true,
            isTagView: true,
            isAffix: false,
          },
          children: [
            {
              id: 101,
              parentId: 10,
              path: "/system/userList",
              name: "userList",
              component: "/src/views/system/userList/index.vue",
              redirect: false,
              isHide: false,
              meta: {
                title: "userList",
                icon: "user",
                isKeepAlive: false,
                isTagView: true,
                isAffix: false,
              },
            },
            {
              id: 102,
              parentId: 10,
              path: "/system/orderList",
              name: "orderList",
              component: "/src/views/system/orderList/index.vue",
              redirect: false,
              isHide: false,
              meta: {
                title: "orderList",
                icon: "user",
                isKeepAlive: false,
                isTagView: true,
                isAffix: false,
              },
            },
            {
              id: 103,
              parentId: 10,
              path: "/system/productList",
              name: "productList",
              component: "/src/views/system/productList/index.vue",
              redirect: false,
              isHide: false,
              meta: {
                title: "productList",
                icon: "user",
                isKeepAlive: false,
                isTagView: true,
                isAffix: false,
              },
            },
            {
              id: 104,
              parentId: 10,
              path: "/system/testList/:id",
              name: "testList",
              component: "/src/views/system/testList/index.vue",
              redirect: false,
              isHide: true,
              meta: {
                title: "testList",
                icon: "user",
                isKeepAlive: false,
                isTagView: true,
                isAffix: false,
              },
            },
            {
              id: 105,
              parentId: 10,
              path: "/system/topicList/:id",
              name: "topicList",
              component: "/src/views/system/topicList/index.vue",
              redirect: false,
              isHide: true,
              meta: {
                title: "topicList",
                icon: "user",
                isKeepAlive: false,
                isTagView: true,
                isAffix: false,
              },
            },
          ],
        },
        {
          id: 9,
          parentId: 1,
          path: "/statistics",
          name: "statistics",
          component: "Layout",
          redirect: "/statistics/distributionOrderList",
          isHide: false,
          meta: {
            title: "statistics",
            icon: "menu",
            isKeepAlive: true,
            isTagView: true,
            isAffix: false,
          },
          children: [
            {
              id: 100,
              parentId: 9,
              path: "/statistics/distributionOrderList",
              name: "distributionOrderList",
              component: "/src/views/statistics/distributionOrderList/index.vue",
              redirect: false,
              isHide: false,
              meta: {
                title: "distributionOrderList",
                icon: "ziti",
                isKeepAlive: false,
                isTagView: true,
                isAffix: false,
              },
            },
            {
              id: 101,
              parentId: 9,
              path: "/statistics/distributionPurseList",
              name: "distributionPurseList",
              component: "/src/views/statistics/distributionPurseList/index.vue",
              redirect: false,
              isHide: false,
              meta: {
                title: "distributionPurseList",
                icon: "ziti",
                isKeepAlive: false,
                isTagView: true,
                isAffix: false,
              },
            },
            {
              id: 102,
              parentId: 9,
              path: "/statistics/distributionTestList",
              name: "distributionTestList",
              component: "/src/views/statistics/distributionTestList/index.vue",
              redirect: false,
              isHide: false,
              meta: {
                title: "distributionTestList",
                icon: "ziti",
                isKeepAlive: false,
                isTagView: true,
                isAffix: false,
              },
            },
            {
              id: 103,
              parentId: 9,
              path: "/statistics/payoutList",
              name: "payoutList",
              component: "/src/views/statistics/payoutList/index.vue",
              redirect: false,
              isHide: false,
              meta: {
                title: "payoutList",
                icon: "ziti",
                isKeepAlive: false,
                isTagView: true,
                isAffix: false,
              },
            },
          ]
        },
        // {
        //   id: 11,
        //   parentId: 1,
        //   path: "/testManager",
        //   name: "testManager",
        //   component: "Layout",
        //   redirect: "/system/user",
        //   isHide: false,
        //   meta: {
        //     title: "testManager",
        //     icon: "system",
        //     isKeepAlive: true,
        //     isTagView: true,
        //     isAffix: false,
        //   },
        //   children: [
        //     {
        //       id: 111,
        //       parentId: 10,
        //       path: "/testManager/list",
        //       name: "testManager_list",
        //       component: "/src/views/manager/index.vue",
        //       redirect: false,
        //       isHide: false,
        //       meta: {
        //         title: "testManager_list",
        //         icon: "menu",
        //         isKeepAlive: true,
        //         isTagView: true,
        //         isAffix: false,
        //       },
        //     }
        //   ],
        // },
        // {
        //   id: 20,
        //   parentId: 1,
        //   path: "/menu",
        //   name: "menu",
        //   component: "Layout",
        //   redirect: "/menu/menu-1",
        //   isHide: false,
        //   meta: {
        //     title: "nestedRoutes",
        //     icon: "menu",
        //     isKeepAlive: true,
        //     isTagView: true,
        //     isAffix: false,
        //   },
        //   children: [
        //     {
        //       id: 201,
        //       parentId: 20,
        //       path: "/menu/menu-1",
        //       name: "menu-1",
        //       component: "ParentView",
        //       redirect: "/menu/menu-1/menu-1-1",
        //       isHide: false,
        //       meta: {
        //         title: "menu-1",
        //         icon: "menu",
        //         isKeepAlive: true,
        //         isTagView: true,
        //         isAffix: false,
        //       },
        //       children: [
        //         {
        //           id: 2010,
        //           parentId: 201,
        //           path: "/menu/menu-1/menu-1-1",
        //           name: "menu-1-1",
        //           component: "/src/views/menu/menu-1/menu-1-1/index.vue",
        //           redirect: null,
        //           isHide: false,
        //           meta: {
        //             title: "menu-1-1",
        //             icon: "menu",
        //             isKeepAlive: true,
        //             isTagView: true,
        //             isAffix: false,
        //           },
        //         },
        //         {
        //           id: 2011,
        //           parentId: 201,
        //           path: "/menu/menu-1/menu-1-2",
        //           name: "menu-1-2",
        //           component: "/src/views/menu/menu-1/menu-1-2/index.vue",
        //           redirect: null,
        //           isHide: false,
        //           meta: {
        //             title: "menu-1-2",
        //             icon: "menu",
        //             isKeepAlive: true,
        //             isTagView: true,
        //             isAffix: false,
        //           },
        //         },
        //       ],
        //     },
        //   ],
        // },
        // {
        //   id: 30,
        //   parentId: 1,
        //   path: "/redirect",
        //   name: "redirectTo",
        //   component: "Layout",
        //   isHide: true,
        //   redirect: "/redirect/:path(.*)",
        //   meta: {
        //     title: "redirect",
        //   },
        //   children: [
        //     {
        //       path: "/redirect/:path(.*)",
        //       name: "redirect",
        //       id: 301,
        //       parentID: 30,
        //       isHide: false,
        //       component: "/src/views/redirect/index.vue",
        //       meta: {
        //         title: "redirect",
        //       },
        //     },
        //   ],
        // },
      ],
    },
    code: 200,
    message: "查询菜单成功",
    success: true,
  },
  user: {
    data: {
      pageNum: 1,
      pageSize: 10,
      total: 2,
      list: [
        {
          id: 1,
          account: "admin",
          password: "123456",
          name: "管理员",
          email: "qize953463876@gmail.com",
          mobile: "17683708377",
          phone: "8576288",
          age: 32,
          avatar: null,
          sex: "null",
          createTime: "2021-12-27T22:55:25.000Z",
          updateTime: "2022-01-18T22:34:22.237Z",
          dept: [{ id: 1, parentId: 0, name: "XXX公司", status: 1, description: "根节点", createTime: "2022-01-17T21:28:23.620Z", updateTime: "2022-01-17T19:43:12.222Z" }],
        },
        {
          id: 4,
          account: "admin1",
          password: "1234567",
          name: "管理员",
          email: "qize953463876@gmail.com",
          mobile: "17683708377",
          phone: "8576288",
          age: 32,
          avatar: null,
          sex: "man",
          createTime: "2022-01-19T02:37:07.962Z",
          updateTime: "2022-01-19T02:37:07.962Z",
          dept: [{ id: 1, parentId: 0, name: "XXX公司", status: 1, description: "根节点", createTime: "2022-01-17T21:28:23.620Z", updateTime: "2022-01-17T19:43:12.222Z" }],
        },
      ],
    },
    code: 200,
    message: "获取用户成功",
    success: true,
  },
};
